version: "3.8"

services:
  #Création d'un service BDD sous MariaDB
  ghost_db:
    image: mariadb
    container_name: ghost_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: lucas
      MYSQL_DATABASE: lucas
      MYSQL_USER: lucas
      MYSQL_PASSWORD: lucas
    networks:
      - net_backend
    volumes:
      - mariadb_data:/var/lib/mysql

  #Création d'un service blog sous Ghost
  ghost:
    depends_on:
      - ghost_db
    image: ghost:latest
    container_name: ghost
    restart: always
    environment:
      #DATABASE_CLIENT: mariadb
      GHOST_DB_HOST: ghost_db:3306
      GHOST_DB_USER: lucas
      GHOST_DB_PASSWORD: lucas
      GHOST_DB_NAME: lucas
    networks:
      - net_backend
      - net_frontend
    ports:
      - "8080:2368"
    volumes:
      - ghost_data:/var/lib/ghost/content

networks:
  net_frontend:
  net_backend:
volumes:
  mariadb_data:
  ghost_data:
