version: "3.8"

services:
  #Création d'un service BDD sous MariaDB
  ghost_db:
    image: mariadb
    container_name: ghost_db
    restart: always
    environment:
      MYSQL_DATABASE: ghost_db
      MYSQL_ROOT_PASSWORD: lucas
      MYSQL_USER: lucas
      MYSQL_PASSWORD: lucas
    networks:
      - backend
    volumes:
      - mariadb_data:/var/lib/mysql

  #Création d'un service blog sous Ghost
  ghost:
    depends_on:
      - ghost_db
    image: ghost:latest
    container_name: ghost
    restart: always
    environment:
      database__client: mysql
      database__connection__host: ghost_db
      database__connection__database: ghost_db
      database__connection__user: lucas
      database__connection__password: lucas
      url: http://localhost:8080
    networks:
      - frontend
      - backend
    ports:
      - "8080:2368"
    volumes:
      - ghost_data:/var/lib/ghost/content

networks:
  frontend:
  backend:
volumes:
  mariadb_data:
  ghost_data:
